# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.36.1
# 

Name:       harbour-ordercorrect

# >> macros
# << macros
%define orgname org.nephros.sailfish
%define appname OrderCorrect
%define pkgname %{name}
%define servicebase %{orgname}.%{appname}
%define desktopsrc %SOURCE1

Summary:    OrderCorrect Project
Version:    0.1.0
Release:    0
Group:      Applications
License:    Apache-2.0
URL:        https://github.com/nephros/harbour-ordercorrect
Source0:    https://github.com/nephros/%{name}/archive/v%{version}.tar.gz#/%{name}-%{version}.tar.gz
Source100:  harbour-ordercorrect.yaml
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  qt5-qttools-linguist
BuildRequires:  qt5-qmake
BuildRequires:  sailfish-svg2png
BuildRequires:  qml-rpm-macros
BuildRequires:  desktop-file-utils

%description
%{summary}.


%define please_also ignore this macro
%undefine vendor
%undefine _vendor
%undefine _chum
BuildRequires: sdk-harbour-rpmvalidator

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5  \
    VERSION=\\"%{version}\\" \
    RELEASE=\\"%{release}\\"

%make_build

# >> build post
# << build post

%install
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%check
# >> check
# this is just here so we can include a clean section below:
%clean
echo '=========== Checking for Harbour compatability.'
mkdir -p ~/rpmbuild/OTHER || :
find ~/rpmbuild/RPMS -type f -name %{name}-%{version}*.rpm -exec /usr/libexec/sdk-harbour-rpmvalidator/rpmvalidation.sh -d 0 --no-color {}  \; | tee ~/rpmbuild/OTHER/harbour-validator.log ||:
echo '=========== DONE checking for Harbour compatability.'
# << check

%files
%{_bindir}/*
%{_datadir}/applications/%{name}.desktop
%dir %{_datadir}/%{name}
%dir %{_datadir}/%{name}/translations
%{_datadir}/%{name}/translations/*.qm
%{_datadir}/%{name}/qml/
# >> files
# << files
